# Generated by Django 3.1.7 on 2021-03-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название тарифа')),
                ('sub_title', models.CharField(max_length=50, verbose_name='Под название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('desc_list', models.TextField(verbose_name='Описание услуги')),
                ('active_color', models.CharField(max_length=50, verbose_name='Активный тариф')),
            ],
        ),
    ]
