# Generated by Django 3.1.7 on 2021-03-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name_plural': 'Цена услуг'},
        ),
    ]
