# Generated by Django 3.1.7 on 2021-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20210311_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='price/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='price',
            name='active_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Активный тариф'),
        ),
    ]
