# Generated by Django 3.1.7 on 2021-03-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20210311_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='active_color',
            field=models.CharField(blank=True, help_text='bg-gradient4', max_length=50, null=True, verbose_name='Активный тариф'),
        ),
    ]
