# Generated by Django 3.1.7 on 2021-03-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_auto_20210311_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='active_color',
        ),
    ]
