# Generated by Django 3.1.7 on 2021-03-14 09:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_remove_price_active_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='desc_list',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание услуги'),
        ),
    ]
