# Generated by Django 3.1.7 on 2021-03-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_auto_20210314_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='image',
        ),
    ]
