# Generated by Django 3.1.7 on 2021-03-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help_bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='help/')),
                ('color', models.CharField(choices=[('cd2', 'Желтый'), ('cd3', 'Ярко-Голубой'), ('cd4', 'Оранжевый'), ('cd5', 'Розовый'), ('cd6', 'Ярко-Розовый'), ('cd7', 'Зеленый'), ('cd8', 'Ярко-Голубой'), ('cd9', 'Светлый')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('color', models.CharField(choices=[('card-bg-a', 'Синий'), ('card-bg-b', 'Розовый'), ('card-bg-c', 'Фиолетовый'), ('card-bg-d', 'Пурпурный'), ('card-bg-e', 'Небесный'), ('card-bg-f', 'Зеленый')], max_length=15, verbose_name='Цвета')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
