# Generated by Django 3.1.7 on 2021-03-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help_bus',
            options={'verbose_name_plural': 'Бизнес сферы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Услуги'},
        ),
    ]
