# Generated by Django 3.1.7 on 2021-03-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210311_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='filter',
            field=models.CharField(blank=True, choices=[('website', 'Веб-сайты'), ('graphic', 'Граф.работы')], max_length=50, null=True, verbose_name='Фильтр'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
