# Generated by Django 3.1.7 on 2021-04-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Услуги'},
        ),
    ]
