# Generated by Django 3.1.7 on 2021-03-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Логотип сайта')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание сайта')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('phone_1', models.CharField(blank=True, max_length=14, null=True, verbose_name='Номер телефона 1')),
                ('phone_2', models.CharField(blank=True, max_length=14, null=True, verbose_name='Номер телефона 2')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('whatsapp', models.CharField(blank=True, max_length=13, null=True, verbose_name='WhatsApp номер')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram ссылка')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram для связи')),
                ('aboutus_page', models.TextField(blank=True, null=True, verbose_name='О нас')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
