# Generated by Django 3.1.7 on 2021-03-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='logo',
        ),
        migrations.AddField(
            model_name='setting',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Логотип сайта'),
        ),
        migrations.AddField(
            model_name='setting',
            name='logo_white',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Логотип сайта'),
        ),
    ]
