# Generated by Django 3.1.7 on 2021-03-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210311_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Логотип темный сайта'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo_white',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Логотип светлый сайта'),
        ),
    ]
