# Generated by Django 3.1.7 on 2021-03-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210311_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='keywords',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ключевые слова через запятую'),
        ),
    ]
