# Generated by Django 3.1.7 on 2021-03-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_setting_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address_osh',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес Ош'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес Бишкек'),
        ),
    ]
