# Generated by Django 3.1.7 on 2021-03-14 09:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210311_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='aboutus_page',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='О нас'),
        ),
    ]
