# Generated by Django 3.1.7 on 2021-03-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='statictic/', verbose_name='Фото')),
                ('title', models.CharField(max_length=50, verbose_name='Имя')),
                ('numb', models.CharField(max_length=50, verbose_name='Цифры')),
            ],
            options={
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Команда'},
        ),
    ]
