# Generated by Django 3.1.7 on 2021-04-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20210311_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Команда'},
        ),
    ]
